---

username: "{{ local_username }}"
password: "{{ local_password }}"
#ansible_python_interpreter: /usr/local/bin/python
#user_data_path: "{{ '~/ansible' | expanduser }}"
tkn: "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"

