$ANSIBLE_VAULT;1.1;AES256
38336264346466366432373633316266633763323933323761646530363934326461643837323664
3161353538363363616662653439633863666233303435360a623336383063373964376565616334
64623065663330623633393761616261653836626430373366616637336233343139623539656163
6338303163663133340a373165663765663861316464353933393164633865636161653266633661
30383261383532386263323936323263303833346535383539393232333533636439333939653433
64663638613862626139653933343630323630626563326663646131353133386333353834343261
37356232386663383162633435306536663330663338396637656233613633366466663434623261
66303031613261613439303035366266613034643433386561386164323566363933623032623131
35633535643237316461383639323635353736656434663139393363313962346136316532656536
39313437633734623965336338346539363339663838316639303836663431313734366432303565
61306233373861623861373435313233613066336636326361653664633265303461666566356339
34356132303831393333323732643665316232353736323436633137353136323561356566303865
37313539636239626539393030613962383964616330626230623032653162393932633363346232
64373264306438333438366431613965666139396332303131393438386135636664653661303436
63323237633265646136343736366535303863613632306465643030306563356338616663653637
39333039343637643431326161653439386438323439636534366537636131623364326264383231
34636539323063373765663733643239306336656534373237623431323965386438386564346437
3766313332633439613737373330303234333266383864643531
