---
  
configs:
  - name: " variables de R3 "
    if_lan: 0/0
    address_lan: 192.168.3.1
    subnet_mask_lan: 255.255.255.0
    if_wan1: 2/0
    address_wan1: 10.0.0.10
    subnet_mask_wan: 255.255.255.252
    if_wan2: 2/3
    address_wan2: 10.0.0.5
    range_begin: 192.168.3.5
    range_finish: 192.168.3.100
    pool_name: R3-pool
    network_lan: 192.168.3.0
    wildcard_lan: 0.0.0.255
    network_wan1: 10.0.0.8
    network_wan2: 10.0.0.4
    wildcard_wan: 0.0.0.3
  




